p24_list = ['aˊ', 'aiˊ', 'amˊ', 'angˊ', 'auˊ', 'baˊ', 'baiˊ', 'banˊ', 'bangˊ', 'bauˊ', 'beˊ', 'benˊ', 'beuˊ', 'biˊ', 'biangˊ', 'bienˊ', 'binˊ', 'biongˊ', 'boˊ', 'boiˊ', 'bongˊ', 'buˊ', 'bunˊ', 'caˊ', 'caiˊ', 'camˊ', 'canˊ', 'cauˊ', 'ceˊ', 'cemˊ', 'cenˊ', 'ceuˊ', 'ciiˊ', 'ciimˊ', 'ciinˊ', 'coˊ', 'coiˊ', 'conˊ', 'congˊ', 'cuˊ', 'cuiˊ', 'cunˊ', 'cungˊ', 'daiˊ', 'damˊ', 'danˊ', 'dangˊ', 'demˊ', 'denˊ', 'deuˊ', 'diˊ', 'diaˊ', 'diamˊ', 'diauˊ', 'dienˊ', 'dinˊ', 'diongˊ', 'diuˊ', 'doˊ', 'doiˊ', 'donˊ', 'dongˊ', 'duˊ', 'duiˊ', 'dunˊ', 'dungˊ', 'eˊ', 'emˊ', 'enˊ', 'euˊ', 'faˊ', 'famˊ', 'fanˊ', 'fenˊ', 'fiˊ', 'foiˊ', 'fonˊ', 'fongˊ', 'fuˊ', 'funˊ', 'fungˊ', 'gaˊ', 'gamˊ', 'ganˊ', 'gangˊ', 'gauˊ', 'giˊ', 'giaˊ', 'giamˊ', 'giangˊ', 'giauˊ', 'gieˊ', 'gienˊ', 'gieuˊ', 'gimˊ', 'ginˊ', 'gioˊ', 'giongˊ', 'giuˊ', 'giunˊ', 'giungˊ', 'goˊ', 'goiˊ', 'gonˊ', 'gongˊ', 'guˊ', 'guaˊ', 'guaiˊ', 'guanˊ', 'guangˊ', 'guenˊ', 'guiˊ', 'gungˊ', 'haˊ', 'haiˊ', 'hamˊ', 'hangˊ', 'hauˊ', 'heˊ', 'hemˊ', 'henˊ', 'heuˊ', 'hiˊ', 'hiaˊ', 'hiamˊ', 'hienˊ', 'hieuˊ', 'himˊ', 'hinˊ', 'hioˊ', 'hiongˊ', 'hiuˊ', 'hiunˊ', 'hiungˊ', 'hoˊ', 'honˊ', 'hongˊ', 'iˊ', 'iaˊ', 'iamˊ', 'iangˊ', 'iauˊ', 'ieˊ', 'ienˊ', 'ieuˊ', 'imˊ', 'inˊ', 'ioˊ', 'iongˊ', 'iuˊ', 'iungˊ', 'jiˊ', 'jiaˊ', 'jiamˊ', 'jiangˊ', 'jienˊ', 'jimˊ', 'jinˊ', 'jioˊ', 'jiongˊ', 'jiuˊ', 'jiungˊ', 'kaˊ', 'kaiˊ', 'kamˊ', 'kanˊ', 'kauˊ', 'kiˊ', 'kiaˊ', 'kiamˊ', 'kiangˊ', 'kiauˊ', 'kieˊ', 'kienˊ', 'kieuˊ', 'kimˊ', 'kinˊ', 'kiongˊ', 'kiuˊ', 'kiunˊ', 'koˊ', 'koiˊ', 'konˊ', 'kongˊ', 'kuˊ', 'kuaˊ', 'kuanˊ', 'kuiˊ',
            'kunˊ', 'kungˊ', 'laˊ', 'laiˊ', 'lamˊ', 'lanˊ', 'langˊ', 'lauˊ', 'leˊ', 'lemˊ', 'liˊ', 'liangˊ', 'liauˊ', 'limˊ', 'linˊ', 'lioˊ', 'liongˊ', 'liuˊ', 'liungˊ', 'loˊ', 'lonˊ', 'longˊ', 'luˊ', 'luiˊ', 'lunˊ', 'lungˊ', 'mˊ', 'maˊ', 'maiˊ', 'manˊ', 'mangˊ', 'mauˊ', 'meˊ', 'menˊ', 'meuˊ', 'miˊ', 'miaˊ', 'miangˊ', 'mienˊ', 'minˊ', 'moˊ', 'muˊ', 'munˊ', 'nˊ', 'naˊ', 'naiˊ', 'nanˊ', 'nauˊ', 'neˊ', 'nemˊ', 'nenˊ', 'neuˊ', 'ngˊ', 'ngaˊ', 'ngamˊ', 'nganˊ', 'ngauˊ', 'ngiˊ', 'ngiaˊ', 'ngiamˊ', 'ngiauˊ', 'ngienˊ', 'ngioˊ', 'ngionˊ', 'ngiunˊ', 'ngoˊ', 'ngongˊ', 'niˊ', 'niauˊ', 'nonˊ', 'nongˊ', 'nuˊ', 'oˊ', 'oiˊ', 'onˊ', 'ongˊ', 'paˊ', 'paiˊ', 'panˊ', 'pangˊ', 'pauˊ', 'penˊ', 'peuˊ', 'piˊ', 'piaˊ', 'piangˊ', 'pienˊ', 'pinˊ', 'poˊ', 'poiˊ', 'ponˊ', 'pongˊ', 'puˊ', 'punˊ', 'pungˊ', 'qiˊ', 'qiaˊ', 'qiamˊ', 'qiangˊ', 'qiauˊ', 'qienˊ', 'qimˊ', 'qinˊ', 'qioˊ', 'qionˊ', 'qiongˊ', 'qiuˊ', 'saˊ', 'saiˊ', 'samˊ', 'sanˊ', 'sangˊ', 'sauˊ', 'seˊ', 'semˊ', 'senˊ', 'seuˊ', 'siiˊ', 'siinˊ', 'soˊ', 'soiˊ', 'sonˊ', 'songˊ', 'suˊ', 'suiˊ', 'sunˊ', 'sungˊ', 'taˊ', 'taiˊ', 'tamˊ', 'tanˊ', 'tangˊ', 'teˊ', 'teuˊ', 'tiamˊ', 'tiauˊ', 'tienˊ', 'tinˊ', 'toˊ', 'toiˊ', 'tonˊ', 'tongˊ', 'tuˊ', 'tuiˊ', 'tunˊ', 'tungˊ', 'vaˊ', 'vaiˊ', 'vanˊ', 'veˊ', 'viˊ', 'voˊ', 'voiˊ', 'vongˊ', 'vuˊ', 'vunˊ', 'vungˊ', 'xiˊ', 'xiaˊ', 'xiamˊ', 'xiangˊ', 'xiauˊ', 'xienˊ', 'ximˊ', 'xinˊ', 'xiongˊ', 'xiuˊ', 'xiungˊ', 'zaˊ', 'zaiˊ', 'zamˊ', 'zanˊ', 'zangˊ', 'zauˊ', 'zeˊ', 'zemˊ', 'zenˊ', 'zeuˊ', 'ziiˊ', 'ziimˊ', 'ziinˊ', 'zoˊ', 'zoiˊ', 'zonˊ', 'zongˊ', 'zuˊ', 'zuiˊ', 'zunˊ', 'zungˊ']
p555_list = ['a', 'ag', 'ai', 'am', 'an', 'ang', 'au', 'ba', 'bad', 'bag', 'bai', 'ban', 'bang', 'bau', 'ben', 'bi', 'biag', 'biang', 'bid', 'bied', 'bien', 'bin', 'biong', 'biu', 'bo', 'bog', 'boi', 'bong', 'bu', 'bud', 'bug', 'bun', 'ca', 'cab', 'cad', 'cag', 'cai', 'cam', 'can', 'cang', 'cau', 'ce', 'ced', 'cen', 'ceu', 'cii', 'ciid', 'ciim', 'ciin', 'co', 'cog', 'coi', 'con', 'cong', 'cu', 'cud', 'cug', 'cui', 'cun', 'cung', 'da', 'dab', 'dad', 'dag', 'dai', 'dam', 'dan', 'dang', 'de', 'deb', 'dem', 'den', 'deu', 'di', 'dia', 'diab', 'diag', 'diam', 'diau', 'did', 'dien', 'din', 'diog', 'diu', 'do', 'dog', 'doi', 'don', 'dong', 'du', 'dud', 'dug', 'dui', 'dun', 'dung', 'eb', 'ed', 'em', 'en', 'eu', 'fa', 'fad', 'fag', 'fai', 'fam', 'fan', 'fang', 'fed', 'fi', 'fid', 'fin', 'fo', 'fog', 'fon', 'fong', 'fu', 'fud', 'fug', 'fun', 'fung', 'ga', 'gab', 'gad', 'gai', 'gam', 'gang', 'gau', 'ge', 'gi', 'gia', 'giab', 'giam', 'giang', 'giau', 'gib', 'gid', 'gie', 'gieb', 'gien', 'gieu', 'gim', 'gin', 'giu', 'giug', 'giung', 'go', 'gog', 'goi', 'gon', 'gong', 'gu', 'gua', 'guad', 'guag', 'guai', 'guan', 'gud', 'gued', 'guen', 'gug', 'gui', 'gun', 'gung', 'ha', 'hab', 'had', 'hag', 'hai', 'ham', 'han', 'hang', 'hau', 'he', 'hed', 'hem', 'hen', 'heu', 'hi', 'hia', 'hiab', 'hied', 'hien', 'hieu', 'him', 'hin', 'hio', 'hiong', 'hiu', 'hiun', 'ho', 'hod', 'hog', 'hoi', 'hon', 'hong', 'i', 'ia', 'iab', 'iag', 'iam', 'iang', 'ib', 'id', 'ie', 'ied', 'ien', 'ieu', 'im', 'in', 'io', 'iog', 'iong', 'iu', 'iud', 'iug', 'iui', 'iun', 'iung', 'ji', 'jia', 'jiab', 'jiag', 'jiam', 'jiang', 'jiau', 'jib', 'jid', 'jien', 'jied', 'jim', 'jin', 'jio', 'jiod', 'jiog', 'jiong', 'jiu', 'ka', 'kab', 'kad', 'kag', 'kam', 'kang', 'kau', 'ki', 'kia', 'kiab', 'kiag', 'kiam', 'kiang', 'kiau', 'kib', 'kid', 'kie', 'kied', 'kien', 'kieu', 'kim', 'kin', 'kioi', 'kiu', 'kiug', 'kiun', 'kiung', 'ko', 'kog', 'kon', 'kong', 'ku', 'kua', 'kuai', 'kuan', 'kuang', 'kud', 'kue', 'kug', 'kui', 'kun', 'kung', 'la', 'lab', 'lad', 'lag', 'lai', 'lam', 'lan', 'lang', 'lau', 'leb', 'led', 'lem', 'len', 'leu', 'li', 'lia',
             'liab', 'liag', 'liam', 'liang', 'liau', 'lib', 'lid', 'lied', 'lien', 'lim', 'lin', 'liog', 'liong', 'liu', 'liug', 'liung', 'lo', 'lod', 'log', 'loi', 'lon', 'long', 'lu', 'lud', 'lug', 'lui', 'lun', 'lung', 'ma', 'mad', 'mag', 'mai', 'mam', 'man', 'mang', 'mau', 'me', 'med', 'men', 'meu', 'mi', 'miang', 'mied', 'mien', 'min', 'mo', 'mog', 'moi', 'mong', 'mu', 'mud', 'mug', 'mun', 'mung', 'n', 'na', 'nab', 'nag', 'nai', 'nam', 'nan', 'nang', 'nau', 'ne', 'nem', 'nen', 'neu', 'nga', 'ngab', 'ngad', 'ngai', 'ngam', 'ngan', 'ngang', 'ngau', 'ngi', 'ngia', 'ngiab', 'ngiag', 'ngiam', 'ngiang', 'ngiau', 'ngib', 'ngid', 'ngie', 'ngied', 'ngiem', 'ngien', 'ngieu', 'ngim', 'ngin', 'ngiog', 'ngiong', 'ngiu', 'ngiug', 'ngiun', 'ngiung', 'ngo', 'ngog', 'ngoi', 'ngong', 'ngu', 'nguan', 'ngui', 'ni', 'nid', 'nin', 'niu', 'no', 'nong', 'nu', 'nug', 'nui', 'nun', 'nung', 'o', 'og', 'oi', 'on', 'ong', 'pa', 'pad', 'pag', 'pai', 'pan', 'pang', 'pau', 'ped', 'peu', 'pi', 'piag', 'piang', 'pid', 'pied', 'pien', 'pin', 'piog', 'piu', 'po', 'pog', 'poi', 'pon', 'pong', 'pu', 'pud', 'pug', 'pun', 'pung', 'qi', 'qia', 'qiab', 'qiag', 'qiam', 'qiang', 'qib', 'qid', 'qied', 'qien', 'qin', 'qio', 'qion', 'qiong', 'qiu', 'sa', 'sab', 'sad', 'sag', 'sai', 'sam', 'san', 'sang', 'sau', 'se', 'sem', 'sen', 'seu', 'sii', 'siib', 'siid', 'siin', 'so', 'sod', 'sog', 'soi', 'son', 'song', 'su', 'sud', 'sug', 'sui', 'sun', 'sung', 'ta', 'tab', 'tad', 'tag', 'tai', 'tam', 'tan', 'tang', 'tau', 'ten', 'teu', 'ti', 'tiab', 'tiam', 'tiau', 'tid', 'tien', 'tied', 'tin', 'tiong', 'tiu', 'to', 'tod', 'tog', 'toi', 'ton', 'tong', 'tu', 'tud', 'tug', 'tui', 'tun', 'tung', 'va', 'vad', 'vag', 'van', 'vang', 've', 'ved', 'vi', 'vid', 'vo', 'vog', 'voi', 'von', 'vong', 'vu', 'vud', 'vun', 'vung', 'xi', 'xia', 'xiab', 'xiag', 'xiang', 'xib', 'xid', 'xied', 'xien', 'xim', 'xin', 'xio', 'xiog', 'xiong', 'xiu', 'xiug', 'xiung', 'za', 'zab', 'zad', 'zag', 'zai', 'zam', 'zan', 'zang', 'zau', 'ze', 'zeb', 'zen', 'zeu', 'zii', 'ziim', 'ziin', 'zo', 'zod', 'zoi', 'zon', 'zong', 'zu', 'zud', 'zug', 'zui', 'zun', 'zung']
p11_list = ['aˇ', 'aiˇ', 'angˇ', 'auˇ', 'baˇ', 'baiˇ', 'bangˇ', 'beˇ', 'biˇ', 'boˇ', 'boiˇ', 'bongˇ', 'buˇ', 'caˇ', 'caiˇ', 'camˇ', 'canˇ', 'cangˇ', 'cauˇ', 'ceˇ', 'cemˇ', 'cenˇ', 'ceuˇ', 'ciiˇ', 'ciimˇ', 'ciinˇ', 'coˇ', 'coiˇ', 'conˇ', 'congˇ', 'cuˇ', 'cuiˇ', 'cunˇ', 'cungˇ', 'daˇ', 'damˇ', 'dangˇ', 'dauˇ', 'deˇ', 'demˇ', 'denˇ', 'diˇ', 'diauˇ', 'dinˇ', 'dioˇ', 'diongˇ', 'diuˇ', 'doˇ', 'doiˇ', 'dongˇ', 'duˇ', 'dungˇ', 'eˇ', 'euˇ', 'faˇ', 'faiˇ', 'famˇ', 'fanˇ', 'fenˇ', 'feuˇ', 'fiˇ', 'finˇ', 'foˇ', 'fongˇ', 'fuˇ', 'funˇ', 'fungˇ', 'gaˇ', 'gaiˇ', 'gamˇ', 'gangˇ', 'gauˇ', 'giˇ', 'giamˇ', 'gieˇ', 'giemˇ', 'goˇ', 'goiˇ', 'gongˇ', 'guˇ', 'guaˇ', 'guangˇ', 'gungˇ', 'haˇ', 'haiˇ', 'hamˇ', 'hanˇ', 'hangˇ', 'hauˇ', 'hemˇ', 'henˇ', 'heuˇ', 'hiamˇ', 'hienˇ', 'hieuˇ', 'himˇ', 'hinˇ', 'hiungˇ', 'hoˇ', 'hoiˇ', 'honˇ', 'hongˇ', 'iˇ', 'iaˇ', 'iamˇ', 'iangˇ', 'ieˇ', 'ienˇ', 'ieuˇ', 'imˇ', 'inˇ', 'iongˇ', 'iuˇ', 'iuiˇ', 'iunˇ', 'iungˇ', 'jiˇ', 'jiaˇ', 'jiauˇ', 'jioˇ', 'jiuˇ', 'kaˇ', 'kiˇ', 'kiaˇ', 'kiamˇ', 'kiangˇ', 'kieˇ', 'kiemˇ', 'kienˇ', 'kieuˇ', 'kimˇ', 'kioˇ', 'kiongˇ', 'kiuˇ', 'kiunˇ', 'kiungˇ', 'koˇ', 'kongˇ', 'kuaiˇ', 'kuanˇ', 'kuiˇ', 'laˇ', 'laiˇ', 'lamˇ', 'lanˇ', 'langˇ', 'lauˇ', 'leˇ', 'lemˇ', 'leuˇ', 'liˇ', 'liamˇ', 'liangˇ', 'liauˇ', 'lienˇ', 'limˇ', 'linˇ', 'lionˇ', 'liongˇ',
            'liuˇ', 'liungˇ', 'loˇ', 'loiˇ', 'longˇ', 'luˇ', 'luiˇ', 'lunˇ', 'lungˇ', 'mˇ', 'maˇ', 'maiˇ', 'manˇ', 'mangˇ', 'mauˇ', 'menˇ', 'meuˇ', 'miˇ', 'miangˇ', 'mienˇ', 'minˇ', 'miongˇ', 'moˇ', 'moiˇ', 'mongˇ', 'muˇ', 'munˇ', 'mungˇ', 'nˇ', 'naˇ', 'naiˇ', 'namˇ', 'nanˇ', 'nangˇ', 'nauˇ', 'neˇ', 'nemˇ', 'nenˇ', 'neuˇ', 'ngˇ', 'ngaˇ', 'ngaiˇ', 'ngamˇ', 'nganˇ', 'ngauˇ', 'ngiˇ', 'ngiamˇ', 'ngiangˇ', 'ngiauˇ', 'ngienˇ', 'ngieuˇ', 'ngimˇ', 'nginˇ', 'ngiongˇ', 'ngiuˇ', 'ngiunˇ', 'ngiungˇ', 'ngoˇ', 'ngoiˇ', 'ngongˇ', 'nguanˇ', 'nguiˇ', 'niˇ', 'noˇ', 'nongˇ', 'nuˇ', 'nungˇ', 'oˇ', 'ongˇ', 'paˇ', 'paiˇ', 'panˇ', 'pangˇ', 'pauˇ', 'penˇ', 'peuˇ', 'piˇ', 'piangˇ', 'pienˇ', 'pinˇ', 'piongˇ', 'poˇ', 'poiˇ', 'pongˇ', 'puˇ', 'punˇ', 'pungˇ', 'qiˇ', 'qiaˇ', 'qiangˇ', 'qiauˇ', 'qienˇ', 'qimˇ', 'qinˇ', 'qionˇ', 'qiongˇ', 'qiuˇ', 'qiungˇ', 'saˇ', 'saiˇ', 'samˇ', 'sangˇ', 'sauˇ', 'seˇ', 'senˇ', 'seuˇ', 'siiˇ', 'siinˇ', 'soˇ', 'sonˇ', 'songˇ', 'suˇ', 'suiˇ', 'sunˇ', 'taiˇ', 'tamˇ', 'tanˇ', 'tangˇ', 'tenˇ', 'teuˇ', 'tiˇ', 'tiamˇ', 'tiauˇ', 'tienˇ', 'tinˇ', 'toˇ', 'toiˇ', 'tonˇ', 'tongˇ', 'tuˇ', 'tuiˇ', 'tunˇ', 'tungˇ', 'vaˇ', 'vanˇ', 'vangˇ', 'veˇ', 'viˇ', 'voˇ', 'vonˇ', 'vongˇ', 'vuˇ', 'vunˇ', 'xiˇ', 'xiaˇ', 'xiamˇ', 'xiangˇ', 'xiauˇ', 'xienˇ', 'xioˇ', 'xiongˇ', 'xiuˇ', 'zamˇ', 'zoiˇ', 'zuiˇ']
p312_list = ['aˋ', 'abˋ', 'adˋ', 'agˋ', 'aiˋ', 'amˋ', 'anˋ', 'auˋ', 'baˋ', 'badˋ', 'bagˋ', 'baiˋ', 'banˋ', 'bangˋ', 'bauˋ', 'bedˋ', 'beuˋ', 'biˋ', 'biagˋ', 'biangˋ', 'bidˋ', 'biedˋ', 'bienˋ', 'binˋ', 'biuˋ', 'boˋ', 'bodˋ', 'bogˋ', 'boiˋ', 'bongˋ', 'buˋ', 'budˋ', 'bugˋ', 'bunˋ', 'bungˋ', 'caˋ', 'cabˋ', 'cadˋ', 'cagˋ', 'caiˋ', 'camˋ', 'canˋ', 'cauˋ', 'ceˋ', 'cedˋ', 'ciiˋ', 'ciidˋ', 'ciinˋ', 'coˋ', 'codˋ', 'cogˋ', 'coiˋ', 'congˋ', 'cuˋ', 'cudˋ', 'cugˋ', 'cuiˋ', 'cunˋ', 'cungˋ', 'daˋ', 'dabˋ', 'dadˋ', 'dagˋ', 'daiˋ', 'damˋ', 'danˋ', 'dangˋ', 'debˋ', 'dedˋ', 'demˋ', 'denˋ', 'deuˋ', 'diˋ', 'diabˋ', 'diamˋ', 'diauˋ', 'didˋ', 'diedˋ', 'dienˋ', 'dinˋ', 'doˋ', 'dodˋ', 'dogˋ', 'doiˋ', 'donˋ', 'dongˋ', 'duˋ', 'dudˋ', 'dugˋ', 'duiˋ', 'dunˋ', 'dungˋ', 'eˋ', 'ebˋ', 'edˋ', 'euˋ', 'fabˋ', 'fadˋ', 'fagˋ', 'faiˋ', 'fanˋ', 'fangˋ', 'feˋ', 'feuˋ', 'fiˋ', 'fidˋ', 'foˋ', 'fogˋ', 'fonˋ', 'fongˋ', 'fuˋ', 'fudˋ', 'fugˋ', 'funˋ', 'fungˋ', 'gaˋ', 'gabˋ', 'gadˋ', 'gagˋ', 'gamˋ', 'gangˋ', 'gauˋ', 'giˋ', 'giabˋ', 'giagˋ', 'giamˋ', 'giangˋ', 'giauˋ', 'gibˋ', 'gidˋ', 'gieˋ', 'giedˋ', 'gienˋ', 'gieuˋ', 'gimˋ', 'ginˋ', 'giogˋ', 'giongˋ', 'giuˋ', 'giugˋ', 'giunˋ', 'giungˋ', 'goˋ', 'godˋ', 'gogˋ', 'goiˋ', 'gonˋ', 'gongˋ', 'guˋ', 'guaˋ', 'guadˋ', 'guaiˋ', 'guangˋ', 'gudˋ', 'guedˋ', 'guenˋ', 'gugˋ', 'guiˋ', 'gunˋ', 'gungˋ', 'haˋ', 'habˋ', 'hadˋ', 'hagˋ', 'haiˋ', 'hamˋ', 'hanˋ', 'hauˋ', 'heˋ', 'hedˋ', 'henˋ', 'heuˋ', 'hiˋ', 'hiabˋ', 'hiagˋ', 'hiamˋ', 'hiauˋ', 'hibˋ', 'hidˋ', 'hiedˋ', 'hienˋ', 'hiogˋ', 'hiongˋ', 'hiuˋ', 'hiugˋ', 'hoˋ', 'hodˋ', 'hogˋ', 'hoiˋ', 'iˋ', 'iaˋ', 'iabˋ', 'iamˋ', 'iangˋ', 'ibˋ', 'idˋ', 'iedˋ', 'ienˋ', 'ieuˋ', 'imˋ', 'inˋ', 'ioˋ', 'iogˋ', 'iongˋ', 'iuˋ', 'iudˋ', 'iugˋ', 'iunˋ', 'iungˋ', 'jiˋ', 'jiaˋ', 'jiabˋ', 'jiagˋ', 'jiamˋ', 'jiangˋ', 'jiauˋ', 'jidˋ', 'jienˋ', 'jiedˋ', 'jinˋ', 'jioˋ', 'jiogˋ', 'jiongˋ', 'jiuˋ', 'jiugˋ', 'jiungˋ', 'kaˋ', 'kabˋ', 'kadˋ', 'kamˋ', 'kauˋ', 'kiˋ', 'kiaˋ', 'kiabˋ', 'kiagˋ', 'kiauˋ', 'kibˋ', 'kiebˋ', 'kiedˋ', 'kienˋ', 'kieuˋ', 'kiogˋ', 'kiuˋ', 'kiudˋ', 'kiugˋ', 'kiunˋ', 'kiungˋ', 'koˋ', 'kogˋ', 'koiˋ', 'konˋ', 'kongˋ', 'kuˋ', 'kuaˋ', 'kuagˋ', 'kuanˋ', 'kudˋ', 'kugˋ', 'kuiˋ', 'kunˋ', 'kungˋ', 'laˋ',
             'labˋ', 'ladˋ', 'lagˋ', 'laiˋ', 'lamˋ', 'lauˋ', 'leˋ', 'lebˋ', 'leuˋ', 'liˋ', 'liaˋ', 'liabˋ', 'liagˋ', 'liamˋ', 'liangˋ', 'liauˋ', 'libˋ', 'lidˋ', 'lienˋ', 'limˋ', 'linˋ', 'lioˋ', 'liongˋ', 'liuˋ', 'liugˋ', 'liungˋ', 'loˋ', 'lodˋ', 'logˋ', 'loiˋ', 'lonˋ', 'longˋ', 'luˋ', 'ludˋ', 'lugˋ', 'luiˋ', 'lungˋ', 'mˋ', 'maˋ', 'madˋ', 'magˋ', 'manˋ', 'mangˋ', 'meˋ', 'medˋ', 'menˋ', 'meuˋ', 'miˋ', 'mienˋ', 'minˋ', 'miongˋ', 'mogˋ', 'moiˋ', 'mongˋ', 'muˋ', 'mudˋ', 'mugˋ', 'mungˋ', 'nˋ', 'naˋ', 'nadˋ', 'nagˋ', 'naiˋ', 'namˋ', 'nauˋ', 'neˋ', 'nedˋ', 'nemˋ', 'neuˋ', 'ngˋ', 'ngaˋ', 'ngabˋ', 'ngadˋ', 'ngamˋ', 'ngiˋ', 'ngiaˋ', 'ngiabˋ', 'ngiagˋ', 'ngiamˋ', 'ngiauˋ', 'ngidˋ', 'ngiedˋ', 'ngienˋ', 'ngieuˋ', 'ngiogˋ', 'ngiongˋ', 'ngiuˋ', 'ngiugˋ', 'ngiunˋ', 'ngoˋ', 'ngogˋ', 'nguanˋ', 'ngudˋ', 'nguiˋ', 'niˋ', 'niauˋ', 'noˋ', 'nogˋ', 'nonˋ', 'nongˋ', 'nuˋ', 'nugˋ', 'nuiˋ', 'nunˋ', 'nungˋ', 'oˋ', 'odˋ', 'ogˋ', 'oiˋ', 'ongˋ', 'paˋ', 'padˋ', 'pagˋ', 'peuˋ', 'piˋ', 'piagˋ', 'pidˋ', 'piedˋ', 'pienˋ', 'pinˋ', 'piongˋ', 'poˋ', 'pogˋ', 'pongˋ', 'puˋ', 'pudˋ', 'pugˋ', 'pungˋ', 'qiˋ', 'qiaˋ', 'qiabˋ', 'qiagˋ', 'qiamˋ', 'qiangˋ', 'qidˋ', 'qiedˋ', 'qienˋ', 'qimˋ', 'qinˋ', 'qiogˋ', 'qionˋ', 'qiongˋ', 'qiuˋ', 'qiugˋ', 'saˋ', 'sabˋ', 'sadˋ', 'sagˋ', 'saiˋ', 'samˋ', 'sanˋ', 'sangˋ', 'seˋ', 'sebˋ', 'sedˋ', 'senˋ', 'seuˋ', 'siiˋ', 'siibˋ', 'siidˋ', 'siimˋ', 'soˋ', 'sodˋ', 'sogˋ', 'songˋ', 'suˋ', 'sudˋ', 'sugˋ', 'suiˋ', 'sunˋ', 'sungˋ', 'tabˋ', 'tadˋ', 'tagˋ', 'taiˋ', 'tamˋ', 'tanˋ', 'teˋ', 'tedˋ', 'tenˋ', 'teuˋ', 'tiˋ', 'tiabˋ', 'tiamˋ', 'tiauˋ', 'tidˋ', 'tienˋ', 'tiedˋ', 'tinˋ', 'tiongˋ', 'toˋ', 'todˋ', 'togˋ', 'tongˋ', 'tuˋ', 'tudˋ', 'tuiˋ', 'tunˋ', 'tungˋ', 'vaˋ', 'vadˋ', 'vagˋ', 'vanˋ', 'vangˋ', 'veˋ', 'vedˋ', 'viˋ', 'vidˋ', 'voˋ', 'vogˋ', 'voiˋ', 'vonˋ', 'vongˋ', 'vuˋ', 'vudˋ', 'vugˋ', 'vunˋ', 'vungˋ', 'xiˋ', 'xiaˋ', 'xiabˋ', 'xiagˋ', 'xiangˋ', 'xibˋ', 'xidˋ', 'xiedˋ', 'xienˋ', 'xiogˋ', 'xiongˋ', 'xiuˋ', 'xiugˋ', 'zaˋ', 'zabˋ', 'zadˋ', 'zagˋ', 'zaiˋ', 'zamˋ', 'zanˋ', 'zangˋ', 'zauˋ', 'zeˋ', 'zebˋ', 'zedˋ', 'zemˋ', 'zeuˋ', 'ziiˋ', 'ziibˋ', 'ziidˋ', 'ziimˋ', 'ziinˋ', 'zoˋ', 'zodˋ', 'zogˋ', 'zonˋ', 'zongˋ', 'zuˋ', 'zudˋ', 'zugˋ', 'zuiˋ', 'zunˋ', 'zungˋ']


def replace_tone(pinyin_array, idx, offset, num, orig="ˊ", tgt="ˇ"):
    for _ in range(num):
        pinyin_array[idx+offset] = pinyin_array[idx+offset].replace(orig, tgt)
        offset += 1
    return pinyin_array


def sixian_sandhi(pinyin_array):
    p24Count = 0
    repeatCount = 1

    for idx, item in enumerate(pinyin_array):
        if idx != 0 and item == pinyin_array[idx-1]:
            repeatCount += 1
        else:
            repeatCount = 1

        if repeatCount == 3:
            if idx+1 != len(pinyin_array) and item == pinyin_array[idx+1]:
                pass
            elif item in p24_list:
                pinyin_array = replace_tone(pinyin_array, idx, -1, 1)
                p24Count = 0
                repeatCount = 1
                continue
            elif item in p11_list:  # vongˇ vongˇ vongˇ → vongˊ vongˇ vongˇ
                pinyin_array = replace_tone(pinyin_array, idx, -2, 1, "ˇ", "ˊ")
                p24Count = 0
                repeatCount = 1
                continue
        elif repeatCount == 4:
            if idx+1 != len(pinyin_array) and pinyin_array[idx+1] == "eˋ":
                # ngoˊ ngoˊ ngoˊ ngoˊ eˋ → ngoˇ ngoˇ ngoˇ ngoˊ eˋ
                pass
            elif item in p24_list:  # ngoˊ ngoˊ ngoˊ ngoˊ → ngoˊ ngoˊ ngoˋ ngoˋ
                pinyin_array = replace_tone(pinyin_array, idx, -1, 2, "ˊ", "ˋ")
                p24Count = 0
                repeatCount = 1
                continue
            elif item in p11_list:  # iongˇ iongˇ iongˇ iongˇ → iongˇ iongˇ iong iong
                pinyin_array = replace_tone(pinyin_array, idx, -1, 2, "ˇ", "")
                p24Count = 0
                repeatCount = 1
                continue

        if item in p24_list:
            p24Count += 1
        elif item in p555_list:
            # samˊ ginˊ fanˊ teu → samˇ ginˇ fanˇ teu
            pinyin_array = replace_tone(pinyin_array, idx, -p24Count, p24Count)
            p24Count = 0
        elif p24Count >= 2:
            # tienˊ ongˊ zeuˊ siinˇ → tienˇ ongˇ zeuˊ siinˇ
            pinyin_array = replace_tone(pinyin_array, idx, -p24Count, p24Count-1)
            p24Count = 0

        if (idx+1 == len(pinyin_array) and p24Count >= 2) or p24Count == 4:
            # xinˊ sangˊ xinˊ sangˊ → xinˇ sangˇ xinˇ sangˊ
            pinyin_array = replace_tone(pinyin_array, idx, -(p24Count-1), p24Count-1)
            p24Count = 0

        if item == "eˋ" and idx != 0 and pinyin_array[idx-1] in p312_list:
            # gieuˋ eˋ → gieuˋ eˇ
            pinyin_array[idx] = "eˇ"

    return pinyin_array
